### PR TITLE
mZCL -> ZCL, ZCL/USD

### PR DESCRIPTION
**Pull request by ch4ot1c**
Please review

### CODE REVIEW

**Comment by ch4ot1c** [comment]
#20

**Review by ghost — APPROVED** [review]
utACK

**Comment by sulmone** [comment]
Why does this still have all of the upstream master branch changes...I thought we were building this release off of the stable 3.0.5 release.

**Comment by ch4ot1c** [comment]
Cherrypicked the needed things; will do this upstream merge in a separate PR.

**Pull request closed without merging**
